### ISSUE TITLE
Markdown linting

### ISSUE THREAD

**Issue by jcalcaben** [magento/glossary#18]
## Problem

There is no linting done on the markdown content of the project making the format varied and hard to read/review sometimes.

## Proposed Solution

- [x] Add a markdown linter to the project 

## Expected Outcome

A markdown linter is added to the project along with an npm command for running it.

**NOTE:**
_There is no expectations for fixing the current content based on linting results._
_In fact, it is not recommended to add such a change in a PR for this issue as it will make it hard to review._

**Comment by dshevtsov** [comment]
The project includes [SuperLinter](https://github.com/github/super-linter) which is run in checks on every pull request as a [GitHub workflow](https://github.com/magento/glossary/blob/main/.github/workflows/linter.yml).
